/*
 * Care Plan Generator
 *
 * Care Plan Generator holds logic for generating CarePlan, Goal and Task from Templates together with auto assignment to correct providers from given Care Team
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	"net/http"

	sw "github.com/GrivIN/go-server-server-generated/go"
)

func main() {
	log.Printf("Server started")

	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
