/*
 * Care Plan Generator
 *
 * Care Plan Generator holds logic for generating CarePlan, Goal and Task from Templates together with auto assignment to correct providers from given Care Team
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ServerErrorResponse struct {

	// Short error description
	Message string `json:"message,omitempty"`

	// Error code number, match http status code
	Code int32 `json:"code,omitempty"`

	// Error category name
	Type_ string `json:"type,omitempty"`

	// Long error description
	DetailedMessage string `json:"detailed_message,omitempty"`
}
