/*
 * Care Plan Generator
 *
 * Care Plan Generator holds logic for generating CarePlan, Goal and Task from Templates together with auto assignment to correct providers from given Care Team
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SuccessResponse struct {

	// FHIRr4 Resource name
	Resource string `json:"resource,omitempty"`

	// Url to newly created resource
	Url string `json:"url,omitempty"`
}
