/*
 * Care Plan Generator
 *
 * Care Plan Generator holds logic for generating CarePlan, Goal and Task from Templates together with auto assignment to correct providers from given Care Team
 *
 * API version: 0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"PlansCarePlanIdGoalsInstantiatePost",
		strings.ToUpper("Post"),
		"/plans/{carePlanId}/goals/instantiate",
		PlansCarePlanIdGoalsInstantiatePost,
	},

	Route{
		"PlansCarePlanIdTasksInstantiatePost",
		strings.ToUpper("Post"),
		"/plans/{carePlanId}/tasks/instantiate",
		PlansCarePlanIdTasksInstantiatePost,
	},

	Route{
		"PlansInstantiatePost",
		strings.ToUpper("Post"),
		"/plans/instantiate",
		PlansInstantiatePost,
	},
}
